id: PA4C42F9C
initial_creation_type: input
source_metadata:
  title: Northern Treasures Series
  language: de
  description: 'Texts related to the so-called Northern Treasures or Jangter/Changter
    (byang gter) tradition:'
  volume:
    51cab1b4527044d19fa2bdbc8cd9ed34:
      title: The Powerful Prayer of Aspiration from the Tantra of the Great Perfection
        that Reveals the All-Penetrating Wisdom Mind of Samantabhadra (Kunzang Mönlam)
      parent: Aspiration Prayers
    fcfbced9dbc8458aa4f98fe3e7096a4a:
      title: 'The Wish-Fulfilling Jewel: A Daily Sādhana of the Noble Avalokiteśvara'
      parent: Sādhanas
    95ec874231c04a98a74918279c358693:
      title: The Means for Accomplishment called the Blazing Wheel
      parent: Sādhanas
created_at: '2022-03-01T04:52:29.100775'
last_modified_at: '2022-03-01T04:52:29.100777'
